const router = require('express').Router();
const c = require('../controllers/userController');
const { protect } = require('../middleware/auth');
const { authorize } = require('../middleware/role');
const { requestLogger } = require('../middleware/logger');
router.use(protect, authorize('admin'), requestLogger);
router.get('/', c.getUsers);
router.get('/:id', c.getUser);
router.post('/', c.createUser);
router.put('/:id', c.updateUser);
router.delete('/:id', c.deleteUser);
module.exports = router;
